[[redirects]]
  from = "https://www.havven.io/*"
  to = "https://www.synthetix.io/:splat"
  status = 301

[[redirects]]
  from = "https://havven.io/*"
  to = "https://www.synthetix.io/:splat"
  status = 301

[[redirects]]
  from = "https://staging.havven.io/*"
  to = "https://www.synthetix.io/:splat"
  status = 301
