[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "10.16.3"
  RUBY_VERSION = "2.6.2"

[[redirects]]
  from = "/uploads/litepaper.pdf"
  to = "/uploads/synthetix_litepaper.pdf"

[[redirects]]
  from = "/tokens"
  to = "https://docs.synthetix.io/tokens/list/"
