backend:
  name: github
  repo: havven/synthetix-website-static-cms

media_folder: static/img
public_folder: /img

collections:
# -------- Site Settings --------
- name: "site-settings"
  label: "Site Settings"
  files:
  # -------- Main Site Settings --------
  - name: "main-site-settings"
    label: "Main Site Settings"
    description: "Allows control of the site settings"
    file: "content/siteSettings.json"
    fields:
    - {label: "Site Title", name: "title", widget: "string"}
    - {label: "Meta - Keywords", name: "keywords", widget: "string"}
    - {label: "Meta - Description", name: "description", widget: "string"}
    - {label: "Twitter URL", name: "twitterUrl", widget: "string"}
    - {label: "Medium URL", name: "mediumUrl", widget: "string"}
    - {label: "Discord URL", name: "discordUrl", widget: "string"}
    - {label: "Reddit URL", name: "redditUrl", widget: "string"}
    - {label: "Telegram URL", name: "telegramUrl", widget: "string"}
    - {label: "OG Image", name: "ogImage", widget: "image"}
    - {label: "Site URL", name: "siteUrl", widget: "string"}
    - {label: "Dashboard URL", name: "dashboardUrl", widget: "string"}
    - {label: "Swappr URL", name: "swapprUrl", widget: "string"}
    - {label: "Mintr URL", name: "mintrUrl", widget: "string"}

# -------- Pages --------
- name: "pages"
  label: "Pages"
  files:
  # -------- 404 --------
  - name: "404-page"
    label: "404 Error Page"
    description: "Content for the 404 Error Page"
    file: "content/pages/404.json"
    fields:
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Subheading", name: "subheading", widget: "string"}
    - {label: "Body", name: "body_markdown", widget: "markdown"}
    - label: "Links"
      name: "links"
      widget: "list"
      fields:
      - {label: "Link Text", name: "link_text", widget: "string"}
      - {label: "Link URL", name: "link_url", widget: "string"}

  # -------- Home --------
  - name: "home"
    label: "Home Page"
    description: "Content for the Home Page"
    file: "content/pages/index.json"
    fields:
    - {label: "Meta - Title", name: "metaTitle", widget: "string"}
    - {label: "Meta - Description", name: "metaDescription", widget: "string"}
    - {label: "Heading", name: "heading", widget: "string"}

  # -------- Team --------
  - name: "team"
    label: "Team Page"
    description: "Content for Team Page"
    file: "content/pages/team.json"
    fields:
    - {label: "Page Title", name: "pageTitle", widget: "string"}
    - {label: "Page Description", name: "pageDescription", widget: "string"}
    - label: "Team members"
      name: "teamMembers"
      widget: "list"
      fields:
      - {label: "Full Name", name: "fullName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Bio", name: "bio", widget: "string"}
      - {label: "LinkedIn URL", name: "linkedInUrl", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
    - label: "Open positions"
      name: "openPositions"
      widget: "list"
      required: false
      fields:
        - {label: "Title", name: "title", widget: "string"}

  # -------- How it works --------
  - name: "how-it-works"
    label: "How it works page"
    description: "Content for How it works page"
    file: "content/pages/how-it-works.json"
    fields:
    - {label: "Page Title", name: "pageTitle", widget: "string"}
    - {label: "Page Description", name: "pageDescription", widget: "string"}

  # -------- tokens --------
  - name: "tokens"
    label: "Tokens page"
    description: "Content for Tokens page"
    file: "content/pages/tokens.json"
    fields:
    - {label: "Page Title", name: "pageTitle", widget: "string"}
    - {label: "Page Description", name: "pageDescription", widget: "string"}
    - label: "Tokens"
      name: "tokens"
      widget: "list"
      fields:
      - {label: "Symbol", name: "symbol", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Decimals", name: "decimals", widget: "number"}

# -------- How it works --------
- label: "Top Navigation"
  name: "topNav"
  folder: "content/topNav"
  extension: "json"
  create: true
  fields:
  - {label: "Name", name: "title", widget: "string"}
  - {label: "Key", name: "key", widget: "string"}
  - {label: "Link", name: "link", widget: "string", required: false, default: ""}
  - {label: "Is External", name: "isExt", widget: "boolean", required: false, default: false}
  - {label: "Order", name: "order", widget: "number", required: false, valueType: "float", default: 1 }
  - {label: "Parent", name: "parentMenu", widget: "relation", collection: "topNav", searchFields: ["title","key"],valueField: "key", displayFields: ["key"], required: false, default: "", hint: "Specify a key of the parent menu item."}
