backend:
  name: github
  repo: havven/havven-website-static-cms

media_folder: static/img
public_folder: /img

collections:
# -------- Site Settings --------
- name: "site-settings"
  label: "Site Settings"
  files:
  # -------- Main Site Settings --------
  - name: "main-site-settings"
    label: "Main Site Settings"
    description: "Allows control of the site settings"
    file: "content/siteSettings.json"
    fields:
    - {label: "Site Title", name: "title", widget: "string"}
    - {label: "Meta - Keywords", name: "keywords", widget: "string"}
    - {label: "Meta - Description", name: "description", widget: "string"}
    - {label: "Twitter URL", name: "twitterUrl", widget: "string"}
    - {label: "Medium URL", name: "mediumUrl", widget: "string"}
    - {label: "Discord URL", name: "discordUrl", widget: "string"}
    - {label: "Reddit URL", name: "redditUrl", widget: "string"}
    - {label: "Telegram URL", name: "telegramUrl", widget: "string"}
    - {label: "OG Image", name: "ogImage", widget: "image"}
    - {label: "Site Icon", name: "siteIcon", widget: "image"}

# -------- Pages --------
- name: "pages"
  label: "Pages"
  files:
  # -------- 404 --------
  - name: "404-page"
    label: "404 Error Page"
    description: "Content for the 404 Error Page"
    file: "content/pages/404.json"
    fields:
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Subheading", name: "subheading", widget: "string"}
    - {label: "Body", name: "body_markdown", widget: "markdown"}
    - label: "Links"
      name: "links"
      widget: "list"
      fields:
      - {label: "Link Text", name: "link_text", widget: "string"}
      - {label: "Link URL", name: "link_url", widget: "string"}

  # -------- Home --------
  - name: "home"
    label: "Home Page"
    description: "Content for the Home Page"
    file: "content/pages/index.json"
    fields:
    - {label: "Page Title", name: "pageTitle", widget: "string"}
    - {label: "Page Description", name: "pageDescription", widget: "string"}

  # -------- Team --------
  - name: "team"
    label: "Team Page"
    description: "Content for Team Page"
    file: "content/pages/team.json"
    fields:
    - {label: "Page Title", name: "pageTitle", widget: "string"}
    - {label: "Page Description", name: "pageDescription", widget: "string"}
    - label: "Team members"
      name: "teamMembers"
      widget: "list"
      fields:
      - {label: "Full Name", name: "fullName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Bio", name: "bio", widget: "string"}
      - {label: "LinkedIn URL", name: "linkedInUrl", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  # -------- How it works --------
  - name: "how-it-works"
    label: "How it works page"
    description: "Content for How it works page"
    file: "content/pages/how-it-works.json"
    fields:
    - {label: "Page Title", name: "pageTitle", widget: "string"}
    - {label: "Page Description", name: "pageDescription", widget: "string"}
